[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.args]
NEXT_PUBLIC_API_URL = "https://api.reline.mx"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
